### ISSUE TITLE
Use ES6 syntax where ever possible.

### ISSUE THREAD

**Issue by muneebulrehman** [Nemwel-Boniface/todoList#2]
Hey, Great job with the project. I have a suggestion for you.
- I can see that you have used a for loop for traversing an array which holds the hard coded values. You can rather use forEach() method to do the same.

Good luck with the rest of the project. Happy coding. ⭐😊✌️

**Comment by souad988** [comment]
Hi nemwell you did a great job implementing the requirements .
I have only one thing to mention, since you are displaying a list it's better to use a li tags 
otherwise everything is good

**Comment by Nemwel-Boniface** [comment]
Hello @muneebulrehman  and @souad988 :wave: 

- Thank you for your suggestions. I made all the suggested changes and it should now be perfect as per your recommendations.

Cheers,
#Happycoding
